version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: student-api-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: student_api_db
      MYSQL_USER:
      MYSQL_PASSWORD:
      # Specify additional environment variables for connection info
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306

    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
  student-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: student-api-app
    restart: always
    environment:
      # Pass MySQL connection info as environment variables to the Go app
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER:
      DB_PASSWORD:
      DB_NAME: student_api_db

    ports:
      - "8080:8080"
    depends_on:
      - mysql
